# Generated by Django 2.0.6 on 2018-06-23 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 23, 16, 18, 23, 264483)),
        ),
    ]
