# Generated by Django 2.0.6 on 2018-06-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0003_auto_20180623_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
