# Generated by Django 2.0.6 on 2018-06-23 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0004_auto_20180623_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
