# Generated by Django 2.0.6 on 2018-06-23 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0005_auto_20180623_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
